glossary = {'appending': 'add more element to your list(method) at the final', 'popping': 'deleting elements of your list(method)', 'indentation': 'a blank or empty space produced by indenting', 'pep8': 'Python Enhacement Proposals', 'python': 'made by c', 'dictionaries' : 'an associative array'}

print("Appending:")
print(glossary['appending'].title())
print("\n")
print("Popping:")
print(glossary['popping'].title())
print("\n")
print("Indentation:")
print(glossary['indentation'].title())
print("\n")
print("PEP8:")
print(glossary['pep8'].title())
print("\n")
print("Python:")
print(glossary['python'].title())
print("\n")
print("Dictionaries:")
print(glossary['dictionaries'].title())
